name: 'data-cards'
description: 'GitHub Action data-cards'
author: 'lxKylin'
# 定义输入参数
inputs:
  github_token:
    description: Your GitHub token for authentication.
    required: true
  lang:
    description: 'your lang'
    required: false
    default: en
  juejin_id:
    description: 'your juejin_id'
    required: true
  csdn_name:
    description: 'your csdn username'
    required: true
  # LeetCodeId:
  #   description: 'your LeetCodeId'
  #   required: true
  commit_message:
    description: Commit message of the github action.
    required: false
    default: 'feat: Add Card Image [ci]'
  commit_user:
    description: Commit message of user.
    default: actions
  branch:
    description: 'your target branch'
    required: false
    default: main

outputs:
  result:
    description: 'data-cards'
runs:
  # 脚本运行环境
  using: node16
  main: 'dist/index.js'
