name: Upload Action File

on:
  push:
    branches:
      - action
  workflow_dispatch:

jobs:
  Upload_Action_File:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code # 获取仓库代码
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3 #安装node.js
        with:
          node-version: '16'
      - name: install & build
        run: |
          echo "npm run build"
          npm install
          npm run build
      - name: Upload Action File
        uses: actions/upload-artifact@v2
        with:
          name: index.js
          path: dist
      - name: Download Action File
        uses: actions/download-artifact@v2
        with:
          name: index.js
          path: dist # 指定下载到本地的路径
      - name: Copy Action File to Dist Folder
        run: |
          # 在这里进行文件拷贝操作
          if [ ! -d "dist" ]; then
            mkdir dist
            echo "dist文件夹已创建"
          else
            echo "dist文件夹已存在"
          fi
          mv dist/*.js ./dist
        shell: bash
      - name: Commit and Push Changes
        run: |
          echo "Commit and Push Changes"
          git remote -v
          # git remote add origin https://github.com/lxKylin/juejin-card.git # 一直存在
          echo "${GITHUB_ACTOR}, GITHUB_ACTOR"
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          git add .
          git commit -m "feat: Update Action File"
          # origin 是远程仓库的默认名称，而 HEAD:main 表示将本地的 HEAD 分支（通常是当前分支）推送到远程仓库的 main 分支
          # git push origin HEAD:action
          git push https://$GITHUB_ACTOR:$PAT@github.com/lxKylin/juejin-card.git HEAD:action
        env:
          GH_TOKEN: ${{ secrets.DATA_CARD_TOKEN }}
